CREATE TABLE jwdb.dbo.view_employee (
 user_id nvarchar(45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 zone_id nvarchar(45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 zone_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 department_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 department nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 branch_code nvarchar(45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 branch_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 section_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 section_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 username nvarchar(45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 title nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 firstname nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 lastname nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 email nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 position_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 group_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 group_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 job_level nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 emp_type nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 position2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 create_date varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 update_date varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)